### ISSUE TITLE
Zero json implementation

### ISSUE THREAD

**Issue by valdirmendesdev** [open-abap/zero-json#3]
Hello Lars, how are you?

I found this repository navigating in open-abap and I have a repository that implements json encoder and decoder using zero dependencies. [https://github.com/valdirmendesdev/abap-json-encoder-decoder](https://github.com/valdirmendesdev/abap-json-encoder-decoder)

I will appreciate so much if you check my work to consider to this project.

**Comment by larshp** [comment]
thanks, I'll probably go ahead and delete this repository

note that open-abap now supports some parts of SXML and RTTI

**Comment by valdirmendesdev** [comment]
Thank you @larshp!
